### ISSUE TITLE
Bulk delete

### ISSUE THREAD

**Issue by Autoflow** [wfeller/laravel-batch#3]
Do you have time to extend the sources for bulk delete?

**Comment by wfeller** [comment]
Like this?

```php
User::batchDelete([
   1, // a user id
   $userTwo, // a user model
]);
```

The objective would be to perform only 1 DB query to delete all these models? While still firing model events?

I could probably do it sometime this weekend or next week.

**Comment by Autoflow** [comment]
1 DB query would be perfect.
Fire model events: YES!!
Transaction save: yes
Perhaps: User::batchDelete( Laravel::Collection );
Have no time limit set, so no need to hurry :-)
Would be glad to hear from you.
Best regards.

**Comment by wfeller** [comment]
Can you take a look at https://github.com/wfeller/laravel-batch/tree/add-batch-delete and let me know what you think?
